services:
  - type: web
    name: rainfall-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn RainfallPredection.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: RainfallPredection.settings
      - key: PYTHON_VERSION
        value: 3.9
